services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  pgsql:
    image: postgres:16.4-alpine
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql:data
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  seq:
    image: datalust/seq:latest
    ports: ["${SEQ_PORT}:80"]
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=WHATISTHIS

  mockoon:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3000"]
    ports: ["3000:3000"]
    volumes:
      - ./mockoon/external-services.json:/data:readonly

volumes:
  postgres-data:
